export type SchemaVersion = number | 'latest';

export interface VersionOption {
  value: SchemaVersion;
  label: string;
}

export const BASIC_INFO_VERSIONS: VersionOption[] = [
  { value: 1, label: 'v1' },
  { value: 3, label: 'v3' },
  { value: 4, label: 'v4 (Recommended)' },
];

// AI generated from tiger
// Last updated: 2026-06-29
export const COUNTRY_CONTRACT_VERSIONS: Record<string, VersionOption[]> = {
  ALB: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  ARE: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  ARG: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  ARM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  AUS: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  AUT: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
    { value: 8, label: 'v8' },
  ],
  BEL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  BGD: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
  ],
  BGR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  BIH: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  BLR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  BOL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  BRA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  CAN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  CHE: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  CHL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  CHN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
    { value: 8, label: 'v8' },
  ],
  COL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  CRI: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  CYP: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  CZE: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  DEU: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  DNK: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  DOM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  ECU: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  EGY: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  ESP: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  EST: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  FIN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  FRA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  FRA_SAS: [{ value: 1, label: 'v1' }],
  GBR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  GEO: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  GRC: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  GTM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  HKG: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  HND: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  HRV: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  HUN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  IDN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  IND: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  IRL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  ISL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  ISR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  ITA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  ITA_APL: [{ value: 1, label: 'v1' }],
  JAM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  JPN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  KEN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
  ],
  KGZ: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  KHM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  KOR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  LBN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  LKA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  LTU: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  LUX: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  LVA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  MAR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  MDA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  MEX: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
    { value: 8, label: 'v8' },
  ],
  MKD: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  MLT: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  MNG: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  MUS: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  MYS: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  NGA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  NIC: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  NLD: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  NOR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  NZL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
  ],
  PAK: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  PAN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  PER: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  PHL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  POL: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  PRI: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  PRT: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
    { value: 8, label: 'v8' },
  ],
  PRY: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  ROU: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  SAU: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  SGP: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  SLV: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  SRB: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
  ],
  SVK: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  SVN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  SWE: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  THA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
  ],
  TUN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
  ],
  TUR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
    { value: 6, label: 'v6' },
    { value: 7, label: 'v7' },
  ],
  TWN: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  UGA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  UKR: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  URY: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  USA: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  VNM: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
  XKX: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
  ],
  ZAF: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
  ],
  ZWE: [
    { value: 1, label: 'v1' },
    { value: 2, label: 'v2' },
    { value: 3, label: 'v3' },
    { value: 4, label: 'v4' },
    { value: 5, label: 'v5' },
  ],
};

export const COUNTRY_CONTRACT_VERSIONS_WITH_MULTIPLE_VERSIONS =
  Object.fromEntries(
    Object.entries(COUNTRY_CONTRACT_VERSIONS).filter(
      ([, versions]) => versions.length > 1,
    ),
  ) as Record<string, VersionOption[]>;

export const FORM_TYPES = [
  { value: 'employment_basic_information', label: 'Basic Information' },
  { value: 'contract_details', label: 'Contract Details' },
] as const;

export type FormType = (typeof FORM_TYPES)[number]['value'];
