export type SupportedTypes =
  | 'text'
  | 'number'
  | 'email'
  | 'select'
  | 'multi-select'
  | 'radio'
  | 'fieldset'
  | 'date'
  | 'checkbox'
  | 'textarea'
  | 'money'
  | 'file'
  | 'countries'
  | 'hidden'
  | 'work-schedule';
