// Alpha3 -> country name for the gap report in sync-country-contract-versions.ts.
// Sourced from the BE repo's vendored ISO-3166 dataset, plus FRA_SAS/ITA_APL/XKX
// which the BE repo uses but ISO 3166 doesn't define.
export const COUNTRY_NAMES: Record<string, string> = {
  ALB: 'Albania',
  ARE: 'United Arab Emirates',
  ARG: 'Argentina',
  ARM: 'Armenia',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Belgium',
  BGD: 'Bangladesh',
  BGR: 'Bulgaria',
  BIH: 'Bosnia and Herzegovina',
  BLR: 'Belarus',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CHN: 'China',
  COL: 'Colombia',
  CRI: 'Costa Rica',
  CYP: 'Cyprus',
  CZE: 'Czech Republic',
  DEU: 'Germany',
  DNK: 'Denmark',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ESP: 'Spain',
  EST: 'Estonia',
  FIN: 'Finland',
  FRA: 'France',
  FRA_SAS: 'France (SAS)',
  GBR: 'United Kingdom',
  GEO: 'Georgia',
  GRC: 'Greece',
  GTM: 'Guatemala',
  HKG: 'Hong Kong',
  HND: 'Honduras',
  HRV: 'Croatia',
  HUN: 'Hungary',
  IDN: 'Indonesia',
  IND: 'India',
  IRL: 'Ireland',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  ITA_APL: 'Italy (APL)',
  JAM: 'Jamaica',
  JPN: 'Japan',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  KHM: 'Cambodia',
  KOR: 'South Korea',
  LBN: 'Lebanon',
  LKA: 'Sri Lanka',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MAR: 'Morocco',
  MDA: 'Moldova',
  MEX: 'Mexico',
  MKD: 'North Macedonia',
  MLT: 'Malta',
  MNG: 'Mongolia',
  MUS: 'Mauritius',
  MYS: 'Malaysia',
  NGA: 'Nigeria',
  NIC: 'Nicaragua',
  NLD: 'Netherlands',
  NOR: 'Norway',
  NZL: 'New Zealand',
  PAK: 'Pakistan',
  PAN: 'Panama',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRI: 'Puerto Rico',
  PRT: 'Portugal',
  PRY: 'Paraguay',
  ROU: 'Romania',
  SAU: 'Saudi Arabia',
  SGP: 'Singapore',
  SLV: 'El Salvador',
  SRB: 'Serbia',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  THA: 'Thailand',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TWN: 'Taiwan',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  URY: 'Uruguay',
  USA: 'United States',
  VNM: 'Vietnam',
  XKX: 'Kosovo',
  ZAF: 'South Africa',
  ZWE: 'Zimbabwe',
};

/** "Portugal (PRT)", or just the code if it's not in COUNTRY_NAMES (e.g. the BE repo added a new one). */
export function countryLabel(code: string): string {
  const name = COUNTRY_NAMES[code];
  return name ? `${name} (${code})` : code;
}
